name: Deploying-to-Stage

on:
  push:
    branches: [ master ]

jobs:
  Deploy-to-Stage:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.4.2
    # - uses: actions/setup-node@v3.4.1
    #   with:
    #     node-version: '18'
    #     cache: 'npm'
    # - name: Run Build
    #   run: |
    #       npm install --legacy-peer-deps
    #       CI=false npm run build
    - name: Copy file via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: 22
        script: whoami
    # - name: Copy file via SSH
    #   uses: garygrossgarten/github-action-scp@release
    #   with:
    #    host: ${{ secrets.HOST }}
    #    username: ${{ secrets.SSH_USER }}
    #    privateKey: ${{ secrets.PRIVATE_KEY}}
    #    local: ./build
    #    remote: /home/devops/test/
